version: "3.8"

services:
  actual-budget-mcp:
    build: .
    container_name: actual-budget-mcp
    env_file:
      - stack.env
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optional: Add network configuration if connecting to Actual Budget on same network
    networks:
      - actual

# Optional: Define network if needed
networks:
  actual:
    name: actual
